#!/usr/bin/env bash
# PreToolUse hook: refuse Edit/Write/MultiEdit on generated, vendored, or
# secret files. These are off-limits per repo conventions and accidental
# edits corrupt dependency state.
#
# Reads tool call JSON from stdin (Claude Code hook contract).
# Exit 2 with a stderr message blocks the tool call and is shown to Claude.

set -uo pipefail

input="$(cat)"

# Pull file_path from the JSON payload without requiring jq.
file_path=$(printf '%s' "$input" | sed -n 's/.*"file_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n1)

[[ -z "$file_path" ]] && exit 0

block() {
  printf 'Refusing to edit %s — %s. If you really intend to change this file, do it manually outside Claude.\n' "$file_path" "$1" >&2
  exit 2
}

case "$file_path" in
  */vendor/*)            block "vendor/ is composer-managed" ;;
  */node_modules/*)      block "node_modules/ is npm-managed" ;;
  */composer.lock)       block "composer.lock must change via 'composer update'" ;;
  */package-lock.json)   block "package-lock.json must change via 'npm install'" ;;
  */yarn.lock)           block "yarn.lock must change via 'yarn'" ;;
  */pnpm-lock.yaml)      block "pnpm-lock.yaml must change via 'pnpm install'" ;;
  */.env|*/.env.*)       block ".env files contain secrets" ;;
  *.tsbuildinfo)         block "tsbuildinfo is a TypeScript incremental cache" ;;
  */next-env.d.ts)       block "next-env.d.ts is generated by next dev/build" ;;
esac

exit 0
